project:
  type: website
  output-dir: _site

website:
  title: "Gabrielle Sorresso"
  site-url: "https://gabriellesorresso.com"
  favicon: images/favicon.svg
  navbar:
    background: white
    pinned: true
    left:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
    right:
      - icon: envelope
        href: mailto:gabrielle.sorresso@gmail.com
        aria-label: Email
      - icon: linkedin
        href: https://www.linkedin.com/
        aria-label: LinkedIn
  page-footer:
    background: light
    left: "© 2026 Gabrielle Sorresso"
    right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: false
    smooth-scroll: true
